user:
  name_max_length: 50
  password_min_length: 6
  email_max_length: 255
micropost:
  content_max_length: 140
  avatar_size: 50
  picture_max_size: 5.megabytes
picture_uploader:
  image_size: [400,400]
avatar_user_follow: 30
